# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Buyer_mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(1000, 650)
        Dialog.setStyleSheet("background:qlineargradient(spread:reflect, x1:0.962682, y1:0, x2:0, y2:1, stop:0 rgba(201, 85, 19, 255), stop:1 rgba(67, 28, 6, 255))")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1000, 650))
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 0px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 5px;\n"
"    border: 1px solid grey;\n"
"\n"
"    background-color: rgb(142, 60, 13);\n"
"    color: White;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(89, 37, 8);\n"
"    color: white;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    background-color: lightgray;\n"
"}\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.run_program_btn = QtWidgets.QPushButton(self.tab_2)
        self.run_program_btn.setGeometry(QtCore.QRect(510, 560, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.run_program_btn.setFont(font)
        self.run_program_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.run_program_btn.setObjectName("run_program_btn")
        self.frame_5 = QtWidgets.QFrame(self.tab_2)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1000, 1))
        self.frame_5.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(370, 330, 291, 51))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(32)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background:none;\n"
"color:rgb(255, 255, 255)")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(430, 230, 121, 111))
        self.label_11.setStyleSheet("background: none\n"
"")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.input_adres_deliv = QtWidgets.QLineEdit(self.tab)
        self.input_adres_deliv.setGeometry(QtCore.QRect(520, 70, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_adres_deliv.setFont(font)
        self.input_adres_deliv.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_adres_deliv.setObjectName("input_adres_deliv")
        self.input_phone_for_pay = QtWidgets.QLineEdit(self.tab)
        self.input_phone_for_pay.setGeometry(QtCore.QRect(20, 170, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_phone_for_pay.setFont(font)
        self.input_phone_for_pay.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_phone_for_pay.setText("")
        self.input_phone_for_pay.setObjectName("input_phone_for_pay")
        self.input_fixed_promocode = QtWidgets.QLineEdit(self.tab)
        self.input_fixed_promocode.setGeometry(QtCore.QRect(20, 70, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_fixed_promocode.setFont(font)
        self.input_fixed_promocode.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_fixed_promocode.setObjectName("input_fixed_promocode")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(80, 30, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background: none;\n"
"color: white")
        self.label_6.setObjectName("label_6")
        self.use_txt_promocode_box = QtWidgets.QCheckBox(self.tab)
        self.use_txt_promocode_box.setGeometry(QtCore.QRect(520, 210, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_txt_promocode_box.setFont(font)
        self.use_txt_promocode_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_txt_promocode_box.setObjectName("use_txt_promocode_box")
        self.input_phone_for_deliv = QtWidgets.QLineEdit(self.tab)
        self.input_phone_for_deliv.setGeometry(QtCore.QRect(20, 220, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_phone_for_deliv.setFont(font)
        self.input_phone_for_deliv.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_phone_for_deliv.setObjectName("input_phone_for_deliv")
        self.input_telegram_api = QtWidgets.QLineEdit(self.tab)
        self.input_telegram_api.setGeometry(QtCore.QRect(20, 370, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_telegram_api.setFont(font)
        self.input_telegram_api.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_telegram_api.setObjectName("input_telegram_api")
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setGeometry(QtCore.QRect(500, 0, 1, 540))
        self.frame_6.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 1, 1))
        self.frame_7.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_11 = QtWidgets.QFrame(self.tab)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 1000, 1))
        self.frame_11.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.use_txt_comment_box = QtWidgets.QCheckBox(self.tab)
        self.use_txt_comment_box.setGeometry(QtCore.QRect(520, 270, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_txt_comment_box.setFont(font)
        self.use_txt_comment_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_txt_comment_box.setObjectName("use_txt_comment_box")
        self.use_check_bonus_value_box = QtWidgets.QCheckBox(self.tab)
        self.use_check_bonus_value_box.setGeometry(QtCore.QRect(520, 240, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_check_bonus_value_box.setFont(font)
        self.use_check_bonus_value_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_check_bonus_value_box.setObjectName("use_check_bonus_value_box")
        self.use_clear_bag_box = QtWidgets.QCheckBox(self.tab)
        self.use_clear_bag_box.setGeometry(QtCore.QRect(520, 300, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_clear_bag_box.setFont(font)
        self.use_clear_bag_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_clear_bag_box.setObjectName("use_clear_bag_box")
        self.use_check_grev_box = QtWidgets.QCheckBox(self.tab)
        self.use_check_grev_box.setGeometry(QtCore.QRect(520, 330, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_check_grev_box.setFont(font)
        self.use_check_grev_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_check_grev_box.setObjectName("use_check_grev_box")
        self.use_on_sber_spas_box = QtWidgets.QCheckBox(self.tab)
        self.use_on_sber_spas_box.setGeometry(QtCore.QRect(520, 360, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_on_sber_spas_box.setFont(font)
        self.use_on_sber_spas_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_on_sber_spas_box.setObjectName("use_on_sber_spas_box")
        self.input_check_promocode_price = QtWidgets.QLineEdit(self.tab)
        self.input_check_promocode_price.setGeometry(QtCore.QRect(20, 120, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_check_promocode_price.setFont(font)
        self.input_check_promocode_price.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_check_promocode_price.setObjectName("input_check_promocode_price")
        self.frame_12 = QtWidgets.QFrame(self.tab)
        self.frame_12.setGeometry(QtCore.QRect(0, 540, 1000, 1))
        self.frame_12.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.input_entrance_deliv = QtWidgets.QLineEdit(self.tab)
        self.input_entrance_deliv.setGeometry(QtCore.QRect(520, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_entrance_deliv.setFont(font)
        self.input_entrance_deliv.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_entrance_deliv.setObjectName("input_entrance_deliv")
        self.input_floor_deliv = QtWidgets.QLineEdit(self.tab)
        self.input_floor_deliv.setGeometry(QtCore.QRect(620, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_floor_deliv.setFont(font)
        self.input_floor_deliv.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_floor_deliv.setObjectName("input_floor_deliv")
        self.input_block_deliv = QtWidgets.QLineEdit(self.tab)
        self.input_block_deliv.setGeometry(QtCore.QRect(720, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_block_deliv.setFont(font)
        self.input_block_deliv.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_block_deliv.setObjectName("input_block_deliv")
        self.input_domofon_deliv = QtWidgets.QLineEdit(self.tab)
        self.input_domofon_deliv.setGeometry(QtCore.QRect(820, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_domofon_deliv.setFont(font)
        self.input_domofon_deliv.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_domofon_deliv.setObjectName("input_domofon_deliv")
        self.use_random_adres_box = QtWidgets.QCheckBox(self.tab)
        self.use_random_adres_box.setGeometry(QtCore.QRect(520, 390, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_random_adres_box.setFont(font)
        self.use_random_adres_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_random_adres_box.setObjectName("use_random_adres_box")
        self.input_first_name_for_deliv = QtWidgets.QLineEdit(self.tab)
        self.input_first_name_for_deliv.setGeometry(QtCore.QRect(20, 270, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_first_name_for_deliv.setFont(font)
        self.input_first_name_for_deliv.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_first_name_for_deliv.setObjectName("input_first_name_for_deliv")
        self.input_last_name_for_deliv = QtWidgets.QLineEdit(self.tab)
        self.input_last_name_for_deliv.setGeometry(QtCore.QRect(20, 320, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_last_name_for_deliv.setFont(font)
        self.input_last_name_for_deliv.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_last_name_for_deliv.setObjectName("input_last_name_for_deliv")
        self.use_random_data_for_deliv = QtWidgets.QCheckBox(self.tab)
        self.use_random_data_for_deliv.setGeometry(QtCore.QRect(520, 420, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_random_data_for_deliv.setFont(font)
        self.use_random_data_for_deliv.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_random_data_for_deliv.setObjectName("use_random_data_for_deliv")
        self.input_pool_value = QtWidgets.QLineEdit(self.tab)
        self.input_pool_value.setGeometry(QtCore.QRect(20, 420, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_pool_value.setFont(font)
        self.input_pool_value.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_pool_value.setObjectName("input_pool_value")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 51, 41))
        self.label_12.setStyleSheet("background: none\n"
"")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.save_settings_btn = QtWidgets.QPushButton(self.tab)
        self.save_settings_btn.setGeometry(QtCore.QRect(20, 560, 961, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.save_settings_btn.setFont(font)
        self.save_settings_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.save_settings_btn.setObjectName("save_settings_btn")
        self.use_txt_adres_deliv_box = QtWidgets.QCheckBox(self.tab)
        self.use_txt_adres_deliv_box.setGeometry(QtCore.QRect(520, 150, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_txt_adres_deliv_box.setFont(font)
        self.use_txt_adres_deliv_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_txt_adres_deliv_box.setObjectName("use_txt_adres_deliv_box")
        self.use_promocode_from_lk_box = QtWidgets.QCheckBox(self.tab)
        self.use_promocode_from_lk_box.setGeometry(QtCore.QRect(520, 180, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_promocode_from_lk_box.setFont(font)
        self.use_promocode_from_lk_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_promocode_from_lk_box.setObjectName("use_promocode_from_lk_box")
        self.use_change_poluchatel_from_link_box = QtWidgets.QCheckBox(self.tab)
        self.use_change_poluchatel_from_link_box.setGeometry(QtCore.QRect(520, 450, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_change_poluchatel_from_link_box.setFont(font)
        self.use_change_poluchatel_from_link_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_change_poluchatel_from_link_box.setObjectName("use_change_poluchatel_from_link_box")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.link_bag = QtWidgets.QLineEdit(self.tab_3)
        self.link_bag.setGeometry(QtCore.QRect(20, 120, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.link_bag.setFont(font)
        self.link_bag.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.link_bag.setObjectName("link_bag")
        self.value_bag = QtWidgets.QLineEdit(self.tab_3)
        self.value_bag.setGeometry(QtCore.QRect(20, 170, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.value_bag.setFont(font)
        self.value_bag.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.value_bag.setObjectName("value_bag")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(80, 30, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: none;\n"
"color: white")
        self.label.setObjectName("label")
        self.delite_bag_btn = QtWidgets.QPushButton(self.tab_3)
        self.delite_bag_btn.setGeometry(QtCore.QRect(530, 560, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.delite_bag_btn.setFont(font)
        self.delite_bag_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.delite_bag_btn.setObjectName("delite_bag_btn")
        self.add_bag_btn = QtWidgets.QPushButton(self.tab_3)
        self.add_bag_btn.setGeometry(QtCore.QRect(20, 220, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.add_bag_btn.setFont(font)
        self.add_bag_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.add_bag_btn.setObjectName("add_bag_btn")
        self.list_bag = QtWidgets.QListWidget(self.tab_3)
        self.list_bag.setGeometry(QtCore.QRect(530, 50, 451, 491))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.list_bag.setFont(font)
        self.list_bag.setStyleSheet("QListWidget {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QListWidget:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.list_bag.setObjectName("list_bag")
        self.name_bag = QtWidgets.QLineEdit(self.tab_3)
        self.name_bag.setGeometry(QtCore.QRect(20, 70, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_bag.setFont(font)
        self.name_bag.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.name_bag.setObjectName("name_bag")
        self.frame_10 = QtWidgets.QFrame(self.tab_3)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 1000, 1))
        self.frame_10.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 51, 41))
        self.label_13.setStyleSheet("background: none\n"
"")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.use_txt_proxy_box = QtWidgets.QCheckBox(self.tab_5)
        self.use_txt_proxy_box.setGeometry(QtCore.QRect(20, 180, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_txt_proxy_box.setFont(font)
        self.use_txt_proxy_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_txt_proxy_box.setObjectName("use_txt_proxy_box")
        self.way_to_txt_proxy_btn = QtWidgets.QPushButton(self.tab_5)
        self.way_to_txt_proxy_btn.setGeometry(QtCore.QRect(20, 200, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_txt_proxy_btn.setFont(font)
        self.way_to_txt_proxy_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_txt_proxy_btn.setObjectName("way_to_txt_proxy_btn")
        self.way_to_uses_txt_proxy_btn = QtWidgets.QPushButton(self.tab_5)
        self.way_to_uses_txt_proxy_btn.setGeometry(QtCore.QRect(20, 260, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_uses_txt_proxy_btn.setFont(font)
        self.way_to_uses_txt_proxy_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_uses_txt_proxy_btn.setObjectName("way_to_uses_txt_proxy_btn")
        self.input_mobile_proxy = QtWidgets.QLineEdit(self.tab_5)
        self.input_mobile_proxy.setGeometry(QtCore.QRect(20, 80, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_mobile_proxy.setFont(font)
        self.input_mobile_proxy.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_mobile_proxy.setObjectName("input_mobile_proxy")
        self.input_link_change_mobile_proxy = QtWidgets.QLineEdit(self.tab_5)
        self.input_link_change_mobile_proxy.setGeometry(QtCore.QRect(20, 120, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_link_change_mobile_proxy.setFont(font)
        self.input_link_change_mobile_proxy.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_link_change_mobile_proxy.setObjectName("input_link_change_mobile_proxy")
        self.use_mobile_proxy_box = QtWidgets.QCheckBox(self.tab_5)
        self.use_mobile_proxy_box.setGeometry(QtCore.QRect(20, 60, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_mobile_proxy_box.setFont(font)
        self.use_mobile_proxy_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_mobile_proxy_box.setObjectName("use_mobile_proxy_box")
        self.txt_usue_proxy_way = QtWidgets.QLabel(self.tab_5)
        self.txt_usue_proxy_way.setGeometry(QtCore.QRect(24, 300, 461, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_usue_proxy_way.setFont(font)
        self.txt_usue_proxy_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.txt_usue_proxy_way.setText("")
        self.txt_usue_proxy_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_usue_proxy_way.setObjectName("txt_usue_proxy_way")
        self.txt_proxy_way = QtWidgets.QLabel(self.tab_5)
        self.txt_proxy_way.setGeometry(QtCore.QRect(20, 230, 471, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_proxy_way.setFont(font)
        self.txt_proxy_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.txt_proxy_way.setText("")
        self.txt_proxy_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_proxy_way.setObjectName("txt_proxy_way")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background: none;\n"
"color: white")
        self.label_5.setObjectName("label_5")
        self.frame_8 = QtWidgets.QFrame(self.tab_5)
        self.frame_8.setEnabled(True)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 1000, 1))
        self.frame_8.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.way_to_promocodes_btn = QtWidgets.QPushButton(self.tab_4)
        self.way_to_promocodes_btn.setGeometry(QtCore.QRect(350, 50, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_promocodes_btn.setFont(font)
        self.way_to_promocodes_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_promocodes_btn.setObjectName("way_to_promocodes_btn")
        self.way_to_cookies_btn = QtWidgets.QPushButton(self.tab_4)
        self.way_to_cookies_btn.setGeometry(QtCore.QRect(20, 120, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_cookies_btn.setFont(font)
        self.way_to_cookies_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_cookies_btn.setObjectName("way_to_cookies_btn")
        self.way_to_nvalid_promocodes_btn = QtWidgets.QPushButton(self.tab_4)
        self.way_to_nvalid_promocodes_btn.setGeometry(QtCore.QRect(350, 120, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_nvalid_promocodes_btn.setFont(font)
        self.way_to_nvalid_promocodes_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_nvalid_promocodes_btn.setObjectName("way_to_nvalid_promocodes_btn")
        self.way_to_uses_promo_btn = QtWidgets.QPushButton(self.tab_4)
        self.way_to_uses_promo_btn.setGeometry(QtCore.QRect(350, 190, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_uses_promo_btn.setFont(font)
        self.way_to_uses_promo_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_uses_promo_btn.setObjectName("way_to_uses_promo_btn")
        self.way_to_nvalid_cookies_btn = QtWidgets.QPushButton(self.tab_4)
        self.way_to_nvalid_cookies_btn.setGeometry(QtCore.QRect(20, 260, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_nvalid_cookies_btn.setFont(font)
        self.way_to_nvalid_cookies_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_nvalid_cookies_btn.setObjectName("way_to_nvalid_cookies_btn")
        self.way_to_uses_cookies_btn = QtWidgets.QPushButton(self.tab_4)
        self.way_to_uses_cookies_btn.setGeometry(QtCore.QRect(20, 330, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_uses_cookies_btn.setFont(font)
        self.way_to_uses_cookies_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_uses_cookies_btn.setObjectName("way_to_uses_cookies_btn")
        self.way_to_cookies_in_run_btn = QtWidgets.QPushButton(self.tab_4)
        self.way_to_cookies_in_run_btn.setGeometry(QtCore.QRect(20, 190, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_cookies_in_run_btn.setFont(font)
        self.way_to_cookies_in_run_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_cookies_in_run_btn.setObjectName("way_to_cookies_in_run_btn")
        self.way_to_txt_comment_btn = QtWidgets.QPushButton(self.tab_4)
        self.way_to_txt_comment_btn.setGeometry(QtCore.QRect(686, 50, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_txt_comment_btn.setFont(font)
        self.way_to_txt_comment_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_txt_comment_btn.setObjectName("way_to_txt_comment_btn")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: none;\n"
"color: white")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(347, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background: none;\n"
"color: white")
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(680, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background: none;\n"
"color: white")
        self.label_8.setObjectName("label_8")
        self.cookies_way = QtWidgets.QLabel(self.tab_4)
        self.cookies_way.setGeometry(QtCore.QRect(20, 150, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cookies_way.setFont(font)
        self.cookies_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.cookies_way.setText("")
        self.cookies_way.setTextFormat(QtCore.Qt.AutoText)
        self.cookies_way.setScaledContents(False)
        self.cookies_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cookies_way.setIndent(0)
        self.cookies_way.setObjectName("cookies_way")
        self.cookies_in_run_way = QtWidgets.QLabel(self.tab_4)
        self.cookies_in_run_way.setGeometry(QtCore.QRect(20, 220, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cookies_in_run_way.setFont(font)
        self.cookies_in_run_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.cookies_in_run_way.setText("")
        self.cookies_in_run_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cookies_in_run_way.setObjectName("cookies_in_run_way")
        self.cookies_nvalid_way = QtWidgets.QLabel(self.tab_4)
        self.cookies_nvalid_way.setGeometry(QtCore.QRect(20, 290, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cookies_nvalid_way.setFont(font)
        self.cookies_nvalid_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.cookies_nvalid_way.setText("")
        self.cookies_nvalid_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cookies_nvalid_way.setObjectName("cookies_nvalid_way")
        self.cookies_uses_way = QtWidgets.QLabel(self.tab_4)
        self.cookies_uses_way.setGeometry(QtCore.QRect(20, 360, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cookies_uses_way.setFont(font)
        self.cookies_uses_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.cookies_uses_way.setText("")
        self.cookies_uses_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cookies_uses_way.setObjectName("cookies_uses_way")
        self.txt_promocode_way = QtWidgets.QLabel(self.tab_4)
        self.txt_promocode_way.setGeometry(QtCore.QRect(350, 80, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_promocode_way.setFont(font)
        self.txt_promocode_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.txt_promocode_way.setText("")
        self.txt_promocode_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_promocode_way.setObjectName("txt_promocode_way")
        self.txt_promocode_nvalid_way = QtWidgets.QLabel(self.tab_4)
        self.txt_promocode_nvalid_way.setGeometry(QtCore.QRect(350, 150, 291, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_promocode_nvalid_way.setFont(font)
        self.txt_promocode_nvalid_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.txt_promocode_nvalid_way.setText("")
        self.txt_promocode_nvalid_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_promocode_nvalid_way.setObjectName("txt_promocode_nvalid_way")
        self.txt_promocode_uses_way = QtWidgets.QLabel(self.tab_4)
        self.txt_promocode_uses_way.setGeometry(QtCore.QRect(350, 220, 291, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_promocode_uses_way.setFont(font)
        self.txt_promocode_uses_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.txt_promocode_uses_way.setText("")
        self.txt_promocode_uses_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_promocode_uses_way.setObjectName("txt_promocode_uses_way")
        self.frame_15 = QtWidgets.QFrame(self.tab_4)
        self.frame_15.setGeometry(QtCore.QRect(333, 0, 1, 630))
        self.frame_15.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setGeometry(QtCore.QRect(0, 0, 1, 1))
        self.frame_16.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.txt_cooment_way = QtWidgets.QLabel(self.tab_4)
        self.txt_cooment_way.setGeometry(QtCore.QRect(690, 80, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_cooment_way.setFont(font)
        self.txt_cooment_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.txt_cooment_way.setText("")
        self.txt_cooment_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_cooment_way.setObjectName("txt_cooment_way")
        self.way_to_dont_grev_cookies_btn = QtWidgets.QPushButton(self.tab_4)
        self.way_to_dont_grev_cookies_btn.setGeometry(QtCore.QRect(20, 400, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_dont_grev_cookies_btn.setFont(font)
        self.way_to_dont_grev_cookies_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_dont_grev_cookies_btn.setObjectName("way_to_dont_grev_cookies_btn")
        self.cookies_dont_grev_way = QtWidgets.QLabel(self.tab_4)
        self.cookies_dont_grev_way.setGeometry(QtCore.QRect(20, 430, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cookies_dont_grev_way.setFont(font)
        self.cookies_dont_grev_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.cookies_dont_grev_way.setText("")
        self.cookies_dont_grev_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cookies_dont_grev_way.setObjectName("cookies_dont_grev_way")
        self.frame_19 = QtWidgets.QFrame(self.tab_4)
        self.frame_19.setGeometry(QtCore.QRect(666, 0, 1, 630))
        self.frame_19.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setGeometry(QtCore.QRect(0, 0, 1, 1))
        self.frame_20.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.frame_13 = QtWidgets.QFrame(self.tab_4)
        self.frame_13.setGeometry(QtCore.QRect(0, 0, 1000, 1))
        self.frame_13.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.way_to_dont_chenge_cookies_btn = QtWidgets.QPushButton(self.tab_4)
        self.way_to_dont_chenge_cookies_btn.setGeometry(QtCore.QRect(20, 470, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_dont_chenge_cookies_btn.setFont(font)
        self.way_to_dont_chenge_cookies_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_dont_chenge_cookies_btn.setObjectName("way_to_dont_chenge_cookies_btn")
        self.cookies_dont_change_way = QtWidgets.QLabel(self.tab_4)
        self.cookies_dont_change_way.setGeometry(QtCore.QRect(20, 500, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cookies_dont_change_way.setFont(font)
        self.cookies_dont_change_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.cookies_dont_change_way.setText("")
        self.cookies_dont_change_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cookies_dont_change_way.setObjectName("cookies_dont_change_way")
        self.use_cookies_with_sberID_box = QtWidgets.QCheckBox(self.tab_4)
        self.use_cookies_with_sberID_box.setGeometry(QtCore.QRect(20, 50, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.use_cookies_with_sberID_box.setFont(font)
        self.use_cookies_with_sberID_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_cookies_with_sberID_box.setObjectName("use_cookies_with_sberID_box")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: none;\n"
"color: white")
        self.label_4.setObjectName("label_4")
        self.way_to_txt_adres_btn = QtWidgets.QPushButton(self.tab_4)
        self.way_to_txt_adres_btn.setGeometry(QtCore.QRect(690, 120, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_txt_adres_btn.setFont(font)
        self.way_to_txt_adres_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_txt_adres_btn.setObjectName("way_to_txt_adres_btn")
        self.txt_adres_way = QtWidgets.QLabel(self.tab_4)
        self.txt_adres_way.setGeometry(QtCore.QRect(690, 150, 291, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_adres_way.setFont(font)
        self.txt_adres_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.txt_adres_way.setText("")
        self.txt_adres_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_adres_way.setObjectName("txt_adres_way")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.run_program_btn.setText(_translate("Dialog", "Запустить"))
        self.label_10.setText(_translate("Dialog", "@abuzer_abuzer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Запуск"))
        self.input_adres_deliv.setPlaceholderText(_translate("Dialog", "Адрес доставки"))
        self.input_phone_for_pay.setPlaceholderText(_translate("Dialog", "Номер для оплаты"))
        self.input_fixed_promocode.setPlaceholderText(_translate("Dialog", "Промокод"))
        self.label_6.setText(_translate("Dialog", "Настройки"))
        self.use_txt_promocode_box.setText(_translate("Dialog", "Использовать промокды из txt"))
        self.input_phone_for_deliv.setPlaceholderText(_translate("Dialog", "Номер для замены получателя"))
        self.input_telegram_api.setPlaceholderText(_translate("Dialog", "Telegram API token"))
        self.use_txt_comment_box.setText(_translate("Dialog", "Использовать коментарии к заказам из txt"))
        self.use_check_bonus_value_box.setText(_translate("Dialog", "Проверять скидку по промокоду"))
        self.use_clear_bag_box.setText(_translate("Dialog", "Очищать корзину"))
        self.use_check_grev_box.setText(_translate("Dialog", "Проверить прогрев"))
        self.use_on_sber_spas_box.setText(_translate("Dialog", "Подключать бонусную программу"))
        self.input_check_promocode_price.setPlaceholderText(_translate("Dialog", "Скидка по промокоду"))
        self.input_entrance_deliv.setPlaceholderText(_translate("Dialog", "Подъезд"))
        self.input_floor_deliv.setPlaceholderText(_translate("Dialog", "Этаж"))
        self.input_block_deliv.setPlaceholderText(_translate("Dialog", "Квартира"))
        self.input_domofon_deliv.setPlaceholderText(_translate("Dialog", "Домофон"))
        self.use_random_adres_box.setText(_translate("Dialog", "Использовать рандомный вторичный адрес"))
        self.input_first_name_for_deliv.setPlaceholderText(_translate("Dialog", "Имя для замены получателя"))
        self.input_last_name_for_deliv.setPlaceholderText(_translate("Dialog", "Фамилия для замены получателя"))
        self.use_random_data_for_deliv.setText(_translate("Dialog", "Использовать рандомные данные для подмены получателя"))
        self.input_pool_value.setPlaceholderText(_translate("Dialog", "Кол-во потоков"))
        self.save_settings_btn.setText(_translate("Dialog", "Сохранить настройки"))
        self.use_txt_adres_deliv_box.setText(_translate("Dialog", "Использовать адреса из txt"))
        self.use_promocode_from_lk_box.setText(_translate("Dialog", "Использовать личные промокоды"))
        self.use_change_poluchatel_from_link_box.setText(_translate("Dialog", "Менять получателя ДО создания заказа"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Настройки"))
        self.link_bag.setPlaceholderText(_translate("Dialog", "Ссылка на товар"))
        self.value_bag.setPlaceholderText(_translate("Dialog", "Кол-во товара"))
        self.label.setText(_translate("Dialog", "Добавление товаров"))
        self.delite_bag_btn.setText(_translate("Dialog", "Удалить товар"))
        self.add_bag_btn.setText(_translate("Dialog", "Добавить товар"))
        self.name_bag.setPlaceholderText(_translate("Dialog", "Название товара"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Корзина"))
        self.use_txt_proxy_box.setText(_translate("Dialog", "Использовать прокси из txt"))
        self.way_to_txt_proxy_btn.setText(_translate("Dialog", "Путь к txt с прокси"))
        self.way_to_uses_txt_proxy_btn.setText(_translate("Dialog", "Путь к txt с юзаными прокси"))
        self.input_mobile_proxy.setPlaceholderText(_translate("Dialog", "Мобильные прокси host:port:login:password"))
        self.input_link_change_mobile_proxy.setPlaceholderText(_translate("Dialog", "Ссылка для обновления IP мобильных прокси"))
        self.use_mobile_proxy_box.setText(_translate("Dialog", "Использовать мобильные прокси"))
        self.label_5.setText(_translate("Dialog", "Настройки прокси"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Настройки прокси"))
        self.way_to_promocodes_btn.setText(_translate("Dialog", "Путь к промокодам"))
        self.way_to_cookies_btn.setText(_translate("Dialog", "Путь к cookies"))
        self.way_to_nvalid_promocodes_btn.setText(_translate("Dialog", "Путь к не валидым промокодам"))
        self.way_to_uses_promo_btn.setText(_translate("Dialog", "Путь к юзаным промокодам"))
        self.way_to_nvalid_cookies_btn.setText(_translate("Dialog", "Путь к не валидным cookies"))
        self.way_to_uses_cookies_btn.setText(_translate("Dialog", "Путь к отработанным cookies"))
        self.way_to_cookies_in_run_btn.setText(_translate("Dialog", "Путь к cookies в работе"))
        self.way_to_txt_comment_btn.setText(_translate("Dialog", "Путь к коментариям для заказов"))
        self.label_2.setText(_translate("Dialog", "Пути к Cookies"))
        self.label_3.setText(_translate("Dialog", "Промокоды"))
        self.label_8.setText(_translate("Dialog", "Прочее"))
        self.way_to_dont_grev_cookies_btn.setText(_translate("Dialog", "Путь к не гретым cookies"))
        self.way_to_dont_chenge_cookies_btn.setText(_translate("Dialog", "Путь к куки без замены получателя"))
        self.use_cookies_with_sberID_box.setText(_translate("Dialog", "sberID cookies"))
        self.label_4.setText(_translate("Dialog", "Тип cookies"))
        self.way_to_txt_adres_btn.setText(_translate("Dialog", "Путь к адресам"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Пути к файлам"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
