# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CheckMainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(800, 500)
        Dialog.setStyleSheet("background:qlineargradient(spread:reflect, x1:0.962682, y1:0, x2:0, y2:1, stop:0 rgba(201, 85, 19, 255), stop:1 rgba(67, 28, 6, 255))")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 0px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 5px;\n"
"    border: 1px solid grey;\n"
"\n"
"    background-color: rgb(142, 60, 13);\n"
"    color: White;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(89, 37, 8);\n"
"    color: white;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    background-color: lightgray;\n"
"}\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.start_checker_btn = QtWidgets.QPushButton(self.tab)
        self.start_checker_btn.setGeometry(QtCore.QRect(410, 400, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.start_checker_btn.setFont(font)
        self.start_checker_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.start_checker_btn.setObjectName("start_checker_btn")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(310, 230, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Swis721 LtEx BT")
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background:none;\n"
"color:rgb(255, 255, 255)")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(330, 130, 121, 111))
        self.label_11.setStyleSheet("background: none\n"
"")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.check_sber_bonus_box = QtWidgets.QCheckBox(self.tab_2)
        self.check_sber_bonus_box.setGeometry(QtCore.QRect(20, 140, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.check_sber_bonus_box.setFont(font)
        self.check_sber_bonus_box.setStyleSheet("background:none;\n"
"color: white\n"
"")
        self.check_sber_bonus_box.setObjectName("check_sber_bonus_box")
        self.cookies_way_btn = QtWidgets.QPushButton(self.tab_2)
        self.cookies_way_btn.setGeometry(QtCore.QRect(360, 140, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cookies_way_btn.setFont(font)
        self.cookies_way_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.cookies_way_btn.setObjectName("cookies_way_btn")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(80, 30, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: none;\n"
"color: white")
        self.label.setObjectName("label")
        self.txt_cookies_way = QtWidgets.QLabel(self.tab_2)
        self.txt_cookies_way.setGeometry(QtCore.QRect(360, 170, 421, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_cookies_way.setFont(font)
        self.txt_cookies_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.txt_cookies_way.setTextFormat(QtCore.Qt.AutoText)
        self.txt_cookies_way.setScaledContents(False)
        self.txt_cookies_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_cookies_way.setIndent(0)
        self.txt_cookies_way.setObjectName("txt_cookies_way")
        self.check_status_order_box = QtWidgets.QCheckBox(self.tab_2)
        self.check_status_order_box.setGeometry(QtCore.QRect(20, 170, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.check_status_order_box.setFont(font)
        self.check_status_order_box.setStyleSheet("background:none;\n"
"color: white\n"
"")
        self.check_status_order_box.setObjectName("check_status_order_box")
        self.check_promocode_box = QtWidgets.QCheckBox(self.tab_2)
        self.check_promocode_box.setGeometry(QtCore.QRect(20, 200, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.check_promocode_box.setFont(font)
        self.check_promocode_box.setStyleSheet("background:none;\n"
"color: white\n"
"")
        self.check_promocode_box.setObjectName("check_promocode_box")
        self.save_setting_btn = QtWidgets.QPushButton(self.tab_2)
        self.save_setting_btn.setGeometry(QtCore.QRect(20, 400, 761, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.save_setting_btn.setFont(font)
        self.save_setting_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.save_setting_btn.setObjectName("save_setting_btn")
        self.frame_14 = QtWidgets.QFrame(self.tab_2)
        self.frame_14.setGeometry(QtCore.QRect(0, 0, 800, 1))
        self.frame_14.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.frame_15 = QtWidgets.QFrame(self.tab_2)
        self.frame_15.setGeometry(QtCore.QRect(0, 380, 800, 1))
        self.frame_15.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.input_pool_value = QtWidgets.QLineEdit(self.tab_2)
        self.input_pool_value.setGeometry(QtCore.QRect(20, 70, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_pool_value.setFont(font)
        self.input_pool_value.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_pool_value.setObjectName("input_pool_value")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 51, 41))
        self.label_13.setStyleSheet("background: none\n"
"")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.frame_16 = QtWidgets.QFrame(self.tab_2)
        self.frame_16.setGeometry(QtCore.QRect(340, 0, 1, 380))
        self.frame_16.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.cookies_uses_way_btn = QtWidgets.QPushButton(self.tab_2)
        self.cookies_uses_way_btn.setGeometry(QtCore.QRect(360, 190, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cookies_uses_way_btn.setFont(font)
        self.cookies_uses_way_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.cookies_uses_way_btn.setObjectName("cookies_uses_way_btn")
        self.txt_uses_cookies_way = QtWidgets.QLabel(self.tab_2)
        self.txt_uses_cookies_way.setGeometry(QtCore.QRect(360, 220, 421, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_uses_cookies_way.setFont(font)
        self.txt_uses_cookies_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.txt_uses_cookies_way.setTextFormat(QtCore.Qt.AutoText)
        self.txt_uses_cookies_way.setScaledContents(False)
        self.txt_uses_cookies_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_uses_cookies_way.setIndent(0)
        self.txt_uses_cookies_way.setObjectName("txt_uses_cookies_way")
        self.send_data_telegram_box = QtWidgets.QCheckBox(self.tab_2)
        self.send_data_telegram_box.setGeometry(QtCore.QRect(20, 230, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.send_data_telegram_box.setFont(font)
        self.send_data_telegram_box.setStyleSheet("background:none;\n"
"color: white\n"
"")
        self.send_data_telegram_box.setObjectName("send_data_telegram_box")
        self.input_telegram_api = QtWidgets.QLineEdit(self.tab_2)
        self.input_telegram_api.setGeometry(QtCore.QRect(20, 110, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_telegram_api.setFont(font)
        self.input_telegram_api.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_telegram_api.setObjectName("input_telegram_api")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(360, 30, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: none;\n"
"color: white")
        self.label_4.setObjectName("label_4")
        self.use_cookies_with_sberID_box = QtWidgets.QCheckBox(self.tab_2)
        self.use_cookies_with_sberID_box.setGeometry(QtCore.QRect(360, 70, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_cookies_with_sberID_box.setFont(font)
        self.use_cookies_with_sberID_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_cookies_with_sberID_box.setObjectName("use_cookies_with_sberID_box")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 51, 41))
        self.label_12.setStyleSheet("background: none\n"
"")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(360, 110, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background: none;\n"
"color: white")
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.way_to_txt_proxy_btn = QtWidgets.QPushButton(self.tab_3)
        self.way_to_txt_proxy_btn.setGeometry(QtCore.QRect(20, 200, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_txt_proxy_btn.setFont(font)
        self.way_to_txt_proxy_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_txt_proxy_btn.setObjectName("way_to_txt_proxy_btn")
        self.txt_usue_proxy_way = QtWidgets.QLabel(self.tab_3)
        self.txt_usue_proxy_way.setGeometry(QtCore.QRect(24, 300, 461, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_usue_proxy_way.setFont(font)
        self.txt_usue_proxy_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.txt_usue_proxy_way.setText("")
        self.txt_usue_proxy_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_usue_proxy_way.setObjectName("txt_usue_proxy_way")
        self.input_mobile_proxy = QtWidgets.QLineEdit(self.tab_3)
        self.input_mobile_proxy.setGeometry(QtCore.QRect(20, 80, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_mobile_proxy.setFont(font)
        self.input_mobile_proxy.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_mobile_proxy.setObjectName("input_mobile_proxy")
        self.txt_proxy_way = QtWidgets.QLabel(self.tab_3)
        self.txt_proxy_way.setGeometry(QtCore.QRect(20, 230, 471, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_proxy_way.setFont(font)
        self.txt_proxy_way.setStyleSheet("background: none;\n"
"color: white\n"
"")
        self.txt_proxy_way.setText("")
        self.txt_proxy_way.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_proxy_way.setObjectName("txt_proxy_way")
        self.input_link_change_mobile_proxy = QtWidgets.QLineEdit(self.tab_3)
        self.input_link_change_mobile_proxy.setGeometry(QtCore.QRect(20, 120, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_link_change_mobile_proxy.setFont(font)
        self.input_link_change_mobile_proxy.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_link_change_mobile_proxy.setObjectName("input_link_change_mobile_proxy")
        self.way_to_uses_txt_proxy_btn = QtWidgets.QPushButton(self.tab_3)
        self.way_to_uses_txt_proxy_btn.setGeometry(QtCore.QRect(20, 260, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.way_to_uses_txt_proxy_btn.setFont(font)
        self.way_to_uses_txt_proxy_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_uses_txt_proxy_btn.setObjectName("way_to_uses_txt_proxy_btn")
        self.use_mobile_proxy_box = QtWidgets.QCheckBox(self.tab_3)
        self.use_mobile_proxy_box.setGeometry(QtCore.QRect(20, 60, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_mobile_proxy_box.setFont(font)
        self.use_mobile_proxy_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_mobile_proxy_box.setObjectName("use_mobile_proxy_box")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(80, 30, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background: none;\n"
"color: white")
        self.label_5.setObjectName("label_5")
        self.use_txt_proxy_box = QtWidgets.QCheckBox(self.tab_3)
        self.use_txt_proxy_box.setGeometry(QtCore.QRect(20, 180, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_txt_proxy_box.setFont(font)
        self.use_txt_proxy_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_txt_proxy_box.setObjectName("use_txt_proxy_box")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 51, 41))
        self.label_14.setStyleSheet("background: none\n"
"")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AutoCheck | abuzer_abuzer"))
        self.start_checker_btn.setText(_translate("Dialog", "Запустить"))
        self.label_10.setText(_translate("Dialog", "@abuzer_abuzer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Запуск"))
        self.check_sber_bonus_box.setText(_translate("Dialog", "Проверять бонусы Sber спасибо"))
        self.cookies_way_btn.setText(_translate("Dialog", "Путь к cookies"))
        self.label.setText(_translate("Dialog", "Настройки"))
        self.txt_cookies_way.setText(_translate("Dialog", "Путь к папке"))
        self.check_status_order_box.setText(_translate("Dialog", "Проверять статусы заказов"))
        self.check_promocode_box.setText(_translate("Dialog", "Проверять промокоды"))
        self.save_setting_btn.setText(_translate("Dialog", "Сохранить настройки"))
        self.input_pool_value.setPlaceholderText(_translate("Dialog", "Кол-во потоков"))
        self.cookies_uses_way_btn.setText(_translate("Dialog", "Путь к провереным cookies"))
        self.txt_uses_cookies_way.setText(_translate("Dialog", "Путь к папке"))
        self.send_data_telegram_box.setText(_translate("Dialog", "Отправлять данные в ТГ бота"))
        self.input_telegram_api.setPlaceholderText(_translate("Dialog", "Telegram API"))
        self.label_4.setText(_translate("Dialog", "Тип cookies"))
        self.use_cookies_with_sberID_box.setText(_translate("Dialog", "sberID cookies"))
        self.label_6.setText(_translate("Dialog", "Пути к папакам"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Настройки"))
        self.way_to_txt_proxy_btn.setText(_translate("Dialog", "Путь к txt с прокси"))
        self.input_mobile_proxy.setPlaceholderText(_translate("Dialog", "Мобильные прокси host:port:login:password"))
        self.input_link_change_mobile_proxy.setPlaceholderText(_translate("Dialog", "Ссылка для обновления IP мобильных прокси"))
        self.way_to_uses_txt_proxy_btn.setText(_translate("Dialog", "Путь к txt с юзаными прокси"))
        self.use_mobile_proxy_box.setText(_translate("Dialog", "Использовать мобильные прокси"))
        self.label_5.setText(_translate("Dialog", "Настройки прокси"))
        self.use_txt_proxy_box.setText(_translate("Dialog", "Использовать прокси из txt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Настройки прокси"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
