# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choiseUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(500, 300)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 500, 300))
        self.frame.setStyleSheet("background:qlineargradient(spread:reflect, x1:0.962682, y1:0, x2:0, y2:1, stop:0 rgba(201, 85, 19, 255), stop:1 rgba(67, 28, 6, 255))")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 30, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: none;\n"
"color: white")
        self.label_2.setObjectName("label_2")
        self.accept_btn = QtWidgets.QPushButton(self.frame)
        self.accept_btn.setGeometry(QtCore.QRect(230, 230, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.accept_btn.setFont(font)
        self.accept_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.accept_btn.setObjectName("accept_btn")
        self.auto_reg_radio = QtWidgets.QRadioButton(self.frame)
        self.auto_reg_radio.setGeometry(QtCore.QRect(30, 180, 111, 17))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.auto_reg_radio.setFont(font)
        self.auto_reg_radio.setStyleSheet("background: none;\n"
"color: white;")
        self.auto_reg_radio.setObjectName("auto_reg_radio")
        self.auto_buy_radio = QtWidgets.QRadioButton(self.frame)
        self.auto_buy_radio.setGeometry(QtCore.QRect(30, 220, 111, 17))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.auto_buy_radio.setFont(font)
        self.auto_buy_radio.setStyleSheet("background: none;\n"
"color: white;")
        self.auto_buy_radio.setObjectName("auto_buy_radio")
        self.auto_check_radio = QtWidgets.QRadioButton(self.frame)
        self.auto_check_radio.setGeometry(QtCore.QRect(30, 260, 111, 17))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.auto_check_radio.setFont(font)
        self.auto_check_radio.setStyleSheet("background: none;\n"
"color: white;")
        self.auto_check_radio.setObjectName("auto_check_radio")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(80, 10, 61, 51))
        self.label_9.setStyleSheet("background: none\n"
"")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "abuzer_abuzer"))
        self.label_2.setText(_translate("Dialog", "Выберите программу"))
        self.accept_btn.setText(_translate("Dialog", "Продолжить"))
        self.auto_reg_radio.setText(_translate("Dialog", "AutoReg"))
        self.auto_buy_radio.setText(_translate("Dialog", "AutoBuy"))
        self.auto_check_radio.setText(_translate("Dialog", "AutoCheck"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
