# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Finaly_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(1000, 610)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background:qlineargradient(spread:reflect, x1:0.962682, y1:0, x2:0, y2:1, stop:0 rgba(201, 85, 19, 255), stop:1 rgba(67, 28, 6, 255))")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1000, 610))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 0px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 5px;\n"
"    border: 1px solid grey;\n"
"\n"
"    background-color: rgb(142, 60, 13);\n"
"    color: White;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(89, 37, 8);\n"
"    color: white;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    background-color: lightgray;\n"
"}\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.frame_11 = QtWidgets.QFrame(self.tab_1)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 1000, 1))
        self.frame_11.setStyleSheet("background: rgb(70, 28, 6);\n"
"border: 0px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.start_auto_reg_btn = QtWidgets.QPushButton(self.tab_1)
        self.start_auto_reg_btn.setGeometry(QtCore.QRect(610, 510, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.start_auto_reg_btn.setFont(font)
        self.start_auto_reg_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.start_auto_reg_btn.setObjectName("start_auto_reg_btn")
        self.frame_5 = QtWidgets.QFrame(self.tab_1)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1000, 1))
        self.frame_5.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_10 = QtWidgets.QLabel(self.tab_1)
        self.label_10.setGeometry(QtCore.QRect(400, 290, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Swis721 LtEx BT")
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background:none;\n"
"color:rgb(255, 255, 255)")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_1)
        self.label_11.setGeometry(QtCore.QRect(420, 190, 121, 111))
        self.label_11.setStyleSheet("background: none\n"
"")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.input_url_bag = QtWidgets.QLineEdit(self.tab_2)
        self.input_url_bag.setGeometry(QtCore.QRect(20, 320, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_url_bag.setFont(font)
        self.input_url_bag.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_url_bag.setObjectName("input_url_bag")
        self.input_api_sms_hub = QtWidgets.QLineEdit(self.tab_2)
        self.input_api_sms_hub.setGeometry(QtCore.QRect(20, 220, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_api_sms_hub.setFont(font)
        self.input_api_sms_hub.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_api_sms_hub.setObjectName("input_api_sms_hub")
        self.input_price_number = QtWidgets.QLineEdit(self.tab_2)
        self.input_price_number.setGeometry(QtCore.QRect(20, 170, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_price_number.setFont(font)
        self.input_price_number.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_price_number.setObjectName("input_price_number")
        self.input_number_value = QtWidgets.QLineEdit(self.tab_2)
        self.input_number_value.setGeometry(QtCore.QRect(20, 120, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_number_value.setFont(font)
        self.input_number_value.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_number_value.setObjectName("input_number_value")
        self.input_mail = QtWidgets.QPlainTextEdit(self.tab_2)
        self.input_mail.setGeometry(QtCore.QRect(710, 70, 261, 331))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_mail.setFont(font)
        self.input_mail.setStyleSheet("QPlainTextEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_mail.setObjectName("input_mail")
        self.grev_box = QtWidgets.QCheckBox(self.tab_2)
        self.grev_box.setGeometry(QtCore.QRect(20, 440, 181, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grev_box.sizePolicy().hasHeightForWidth())
        self.grev_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.grev_box.setFont(font)
        self.grev_box.setStyleSheet("background: none;\n"
"color: white")
        self.grev_box.setObjectName("grev_box")
        self.rand_mail_box = QtWidgets.QCheckBox(self.tab_2)
        self.rand_mail_box.setGeometry(QtCore.QRect(20, 410, 171, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rand_mail_box.sizePolicy().hasHeightForWidth())
        self.rand_mail_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rand_mail_box.setFont(font)
        self.rand_mail_box.setStyleSheet("background: none;\n"
"color: white")
        self.rand_mail_box.setObjectName("rand_mail_box")
        self.you_numbers_box = QtWidgets.QCheckBox(self.tab_2)
        self.you_numbers_box.setGeometry(QtCore.QRect(210, 410, 201, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.you_numbers_box.sizePolicy().hasHeightForWidth())
        self.you_numbers_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.you_numbers_box.setFont(font)
        self.you_numbers_box.setStyleSheet("background: none;\n"
"color: white")
        self.you_numbers_box.setObjectName("you_numbers_box")
        self.input_adres_bag = QtWidgets.QLineEdit(self.tab_2)
        self.input_adres_bag.setGeometry(QtCore.QRect(20, 370, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_adres_bag.setFont(font)
        self.input_adres_bag.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_adres_bag.setObjectName("input_adres_bag")
        self.input_pool_value = QtWidgets.QLineEdit(self.tab_2)
        self.input_pool_value.setGeometry(QtCore.QRect(20, 70, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_pool_value.setFont(font)
        self.input_pool_value.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_pool_value.setObjectName("input_pool_value")
        self.input_you_numbers = QtWidgets.QPlainTextEdit(self.tab_2)
        self.input_you_numbers.setGeometry(QtCore.QRect(430, 70, 261, 331))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_you_numbers.setFont(font)
        self.input_you_numbers.setStyleSheet("QPlainTextEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_you_numbers.setObjectName("input_you_numbers")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(80, 30, 311, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: none;\n"
"color: white")
        self.label.setObjectName("label")
        self.frame_10 = QtWidgets.QFrame(self.tab_2)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 1000, 1))
        self.frame_10.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(430, 40, 261, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: none;\n"
"color: white")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(710, 40, 261, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background: none;\n"
"color: white")
        self.label_3.setObjectName("label_3")
        self.frame_12 = QtWidgets.QFrame(self.tab_2)
        self.frame_12.setGeometry(QtCore.QRect(0, 490, 1000, 1))
        self.frame_12.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.activate_sber_spasibo_box = QtWidgets.QCheckBox(self.tab_2)
        self.activate_sber_spasibo_box.setGeometry(QtCore.QRect(210, 440, 321, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activate_sber_spasibo_box.sizePolicy().hasHeightForWidth())
        self.activate_sber_spasibo_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.activate_sber_spasibo_box.setFont(font)
        self.activate_sber_spasibo_box.setStyleSheet("background: none;\n"
"color: white")
        self.activate_sber_spasibo_box.setObjectName("activate_sber_spasibo_box")
        self.save_settings_btn = QtWidgets.QPushButton(self.tab_2)
        self.save_settings_btn.setGeometry(QtCore.QRect(10, 510, 981, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.save_settings_btn.setFont(font)
        self.save_settings_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.save_settings_btn.setObjectName("save_settings_btn")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 51, 41))
        self.label_12.setStyleSheet("background: none\n"
"")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.input_telegram_api = QtWidgets.QLineEdit(self.tab_2)
        self.input_telegram_api.setGeometry(QtCore.QRect(20, 270, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_telegram_api.setFont(font)
        self.input_telegram_api.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_telegram_api.setObjectName("input_telegram_api")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.input_mobile_proxy = QtWidgets.QLineEdit(self.tab_3)
        self.input_mobile_proxy.setGeometry(QtCore.QRect(20, 80, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_mobile_proxy.setFont(font)
        self.input_mobile_proxy.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_mobile_proxy.setObjectName("input_mobile_proxy")
        self.input_link_change_mobile_proxy = QtWidgets.QLineEdit(self.tab_3)
        self.input_link_change_mobile_proxy.setGeometry(QtCore.QRect(20, 120, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_link_change_mobile_proxy.setFont(font)
        self.input_link_change_mobile_proxy.setStyleSheet("QLineEdit {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font-size: 14;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(219, 123, 53);\n"
"}")
        self.input_link_change_mobile_proxy.setObjectName("input_link_change_mobile_proxy")
        self.use_mobile_proxy_box = QtWidgets.QCheckBox(self.tab_3)
        self.use_mobile_proxy_box.setGeometry(QtCore.QRect(20, 60, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_mobile_proxy_box.setFont(font)
        self.use_mobile_proxy_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_mobile_proxy_box.setObjectName("use_mobile_proxy_box")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(80, 30, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background: none;\n"
"color: white")
        self.label_7.setObjectName("label_7")
        self.use_txt_proxy_box = QtWidgets.QCheckBox(self.tab_3)
        self.use_txt_proxy_box.setGeometry(QtCore.QRect(20, 180, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_txt_proxy_box.setFont(font)
        self.use_txt_proxy_box.setStyleSheet("background: none;\n"
"color: white;\n"
"")
        self.use_txt_proxy_box.setObjectName("use_txt_proxy_box")
        self.way_to_uses_txt_proxy_btn = QtWidgets.QPushButton(self.tab_3)
        self.way_to_uses_txt_proxy_btn.setGeometry(QtCore.QRect(20, 280, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.way_to_uses_txt_proxy_btn.setFont(font)
        self.way_to_uses_txt_proxy_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_uses_txt_proxy_btn.setShortcut("")
        self.way_to_uses_txt_proxy_btn.setCheckable(False)
        self.way_to_uses_txt_proxy_btn.setAutoRepeat(False)
        self.way_to_uses_txt_proxy_btn.setAutoExclusive(False)
        self.way_to_uses_txt_proxy_btn.setObjectName("way_to_uses_txt_proxy_btn")
        self.way_to_txt_proxy_btn = QtWidgets.QPushButton(self.tab_3)
        self.way_to_txt_proxy_btn.setGeometry(QtCore.QRect(20, 210, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.way_to_txt_proxy_btn.setFont(font)
        self.way_to_txt_proxy_btn.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_txt_proxy_btn.setShortcut("")
        self.way_to_txt_proxy_btn.setCheckable(False)
        self.way_to_txt_proxy_btn.setAutoRepeat(False)
        self.way_to_txt_proxy_btn.setAutoExclusive(False)
        self.way_to_txt_proxy_btn.setObjectName("way_to_txt_proxy_btn")
        self.proxy_uses_txt_way = QtWidgets.QLabel(self.tab_3)
        self.proxy_uses_txt_way.setGeometry(QtCore.QRect(20, 310, 471, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proxy_uses_txt_way.sizePolicy().hasHeightForWidth())
        self.proxy_uses_txt_way.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.proxy_uses_txt_way.setFont(font)
        self.proxy_uses_txt_way.setStyleSheet("background: none;\n"
"color: white")
        self.proxy_uses_txt_way.setText("")
        self.proxy_uses_txt_way.setObjectName("proxy_uses_txt_way")
        self.proxy_txt_way = QtWidgets.QLabel(self.tab_3)
        self.proxy_txt_way.setGeometry(QtCore.QRect(20, 240, 471, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proxy_txt_way.sizePolicy().hasHeightForWidth())
        self.proxy_txt_way.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.proxy_txt_way.setFont(font)
        self.proxy_txt_way.setStyleSheet("background: none;\n"
"color: white")
        self.proxy_txt_way.setText("")
        self.proxy_txt_way.setObjectName("proxy_txt_way")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 51, 41))
        self.label_13.setStyleSheet("background: none\n"
"")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_13 = QtWidgets.QFrame(self.tab)
        self.frame_13.setGeometry(QtCore.QRect(0, 0, 1000, 1))
        self.frame_13.setStyleSheet("background: white;\n"
"border: 0px;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.cookies_way_nvalid = QtWidgets.QLabel(self.tab)
        self.cookies_way_nvalid.setGeometry(QtCore.QRect(20, 240, 401, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cookies_way_nvalid.sizePolicy().hasHeightForWidth())
        self.cookies_way_nvalid.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cookies_way_nvalid.setFont(font)
        self.cookies_way_nvalid.setStyleSheet("background: none;\n"
"color: white")
        self.cookies_way_nvalid.setText("")
        self.cookies_way_nvalid.setObjectName("cookies_way_nvalid")
        self.wat_nvalid_cookies = QtWidgets.QPushButton(self.tab)
        self.wat_nvalid_cookies.setGeometry(QtCore.QRect(20, 210, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.wat_nvalid_cookies.setFont(font)
        self.wat_nvalid_cookies.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.wat_nvalid_cookies.setShortcut("")
        self.wat_nvalid_cookies.setCheckable(False)
        self.wat_nvalid_cookies.setAutoRepeat(False)
        self.wat_nvalid_cookies.setAutoExclusive(False)
        self.wat_nvalid_cookies.setObjectName("wat_nvalid_cookies")
        self.way_cookies = QtWidgets.QPushButton(self.tab)
        self.way_cookies.setGeometry(QtCore.QRect(20, 140, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.way_cookies.setFont(font)
        self.way_cookies.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_cookies.setObjectName("way_cookies")
        self.cookies_way = QtWidgets.QLabel(self.tab)
        self.cookies_way.setGeometry(QtCore.QRect(20, 170, 401, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cookies_way.sizePolicy().hasHeightForWidth())
        self.cookies_way.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cookies_way.setFont(font)
        self.cookies_way.setStyleSheet("background: none;\n"
"color: white")
        self.cookies_way.setText("")
        self.cookies_way.setObjectName("cookies_way")
        self.way_to_dont_grev_cookies = QtWidgets.QPushButton(self.tab)
        self.way_to_dont_grev_cookies.setGeometry(QtCore.QRect(20, 70, 401, 31))
        self.way_to_dont_grev_cookies.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.way_to_dont_grev_cookies.setFont(font)
        self.way_to_dont_grev_cookies.setStyleSheet("QPushButton {\n"
"    background: rgb(224, 131, 61);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(255, 180, 94);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(152, 65, 14);\n"
"    border: 30px;\n"
"    border-radius: 15px;\n"
"    color: white\n"
"}")
        self.way_to_dont_grev_cookies.setObjectName("way_to_dont_grev_cookies")
        self.cookies_way_dont_greb = QtWidgets.QLabel(self.tab)
        self.cookies_way_dont_greb.setGeometry(QtCore.QRect(20, 100, 401, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cookies_way_dont_greb.sizePolicy().hasHeightForWidth())
        self.cookies_way_dont_greb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cookies_way_dont_greb.setFont(font)
        self.cookies_way_dont_greb.setStyleSheet("background: none;\n"
"color: white")
        self.cookies_way_dont_greb.setText("")
        self.cookies_way_dont_greb.setObjectName("cookies_way_dont_greb")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(80, 30, 311, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: none;\n"
"color: white")
        self.label_4.setObjectName("label_4")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 51, 41))
        self.label_14.setStyleSheet("background: none\n"
"")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AutoReg | abuzer_abuzer"))
        self.start_auto_reg_btn.setText(_translate("Dialog", "Запустить"))
        self.label_10.setText(_translate("Dialog", "@abuzer_abuzer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dialog", "Запуск"))
        self.input_url_bag.setPlaceholderText(_translate("Dialog", "Ссылка на товар"))
        self.input_api_sms_hub.setPlaceholderText(_translate("Dialog", "API-token"))
        self.input_price_number.setPlaceholderText(_translate("Dialog", "Стоимость номера"))
        self.input_number_value.setPlaceholderText(_translate("Dialog", "Кол-во номеров"))
        self.grev_box.setText(_translate("Dialog", "Отключить прогрев"))
        self.rand_mail_box.setText(_translate("Dialog", "Рандомные почты"))
        self.you_numbers_box.setText(_translate("Dialog", "Свои номера"))
        self.input_adres_bag.setPlaceholderText(_translate("Dialog", "Адрес доставки"))
        self.input_pool_value.setPlaceholderText(_translate("Dialog", "Кол-во потоков"))
        self.label.setText(_translate("Dialog", "Настройки"))
        self.label_2.setText(_translate("Dialog", "Физ-номера"))
        self.label_3.setText(_translate("Dialog", "Почты"))
        self.activate_sber_spasibo_box.setText(_translate("Dialog", "Включать бонусы СберСпасибо"))
        self.save_settings_btn.setText(_translate("Dialog", "Сохранить настройки"))
        self.input_telegram_api.setPlaceholderText(_translate("Dialog", "API token Telegram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Настройки"))
        self.input_mobile_proxy.setPlaceholderText(_translate("Dialog", "Мобильные прокси host:port:login:password"))
        self.input_link_change_mobile_proxy.setPlaceholderText(_translate("Dialog", "Ссылка для обновления IP мобильных прокси"))
        self.use_mobile_proxy_box.setText(_translate("Dialog", "Использовать мобильные прокси"))
        self.label_7.setText(_translate("Dialog", "Настройки прокси"))
        self.use_txt_proxy_box.setText(_translate("Dialog", "Использовать прокси из txt"))
        self.way_to_uses_txt_proxy_btn.setText(_translate("Dialog", "Путь к прокси"))
        self.way_to_txt_proxy_btn.setText(_translate("Dialog", "Путь к прокси"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Настройки прокси"))
        self.wat_nvalid_cookies.setText(_translate("Dialog", "Путь к невалидным cookie"))
        self.way_cookies.setText(_translate("Dialog", "Путь к cookie"))
        self.way_to_dont_grev_cookies.setText(_translate("Dialog", "Путь к негретым cookies"))
        self.label_4.setText(_translate("Dialog", "Пути к файлам"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Пути к файлам"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
